import { Transaction, RewardTier } from '@/lib/types';

export const userTransactions: Transaction[] = [
  {
    id: '1',
    type: 'Swap',
    status: 'Completed',
    fromToken: 'BNB',
    toToken: 'DRC',
    fromAmount: 0.5,
    toAmount: 1200,
    date: '2024-05-20T14:48:00.000Z',
    txHash: '0xabc...123',
  },
  {
    id: '2',
    type: 'Reward Claim',
    status: 'Completed',
    rewardTier: 'Lagos Bonus',
    rewardAmount: 10,
    date: '2024-05-19T10:30:00.000Z',
    txHash: '0xdef...456',
  },
  {
    id: '3',
    type: 'Swap',
    status: 'Failed',
    fromToken: 'USDT',
    toToken: 'DRC',
    fromAmount: 100,
    toAmount: 240,
    date: '2024-05-18T09:15:00.000Z',
    txHash: '0xghi...789',
  },
    {
    id: '4',
    type: 'Reward Claim',
    status: 'Completed',
    rewardTier: 'Cairo Reward',
    rewardAmount: 25,
    date: '2024-05-21T11:00:00.000Z',
    txHash: '0xjkl...abc',
  },
  {
    id: '5',
    type: 'Swap',
    status: 'Pending',
    fromToken: 'BNB',
    toToken: 'DRC',
    fromAmount: 1.2,
    toAmount: 2880,
    date: new Date().toISOString(),
    txHash: '0xmno...def',
  },
];

export const userRewards: RewardTier[] = [
  {
    id: 'lagos',
    name: 'Lagos Bonus',
    tier: 'Lagos Bonus',
    trigger: 'First wallet connection',
    reward: 10,
    status: 'claimed',
    progress: 100,
  },
  {
    id: 'cairo',
    name: 'Cairo Reward',
    tier: 'Cairo Reward',
    trigger: 'First token swap',
    reward: 25,
    status: 'claimed',
    progress: 100,
  },
  {
    id: 'nairobi',
    name: 'Nairobi Treasure',
    tier: 'Nairobi Treasure',
    trigger: '3+ swaps per week',
    reward: 50,
    status: 'unclaimed',
    progress: 66,
  },
  {
    id: 'accra',
    name: 'Accra Champion',
    tier: 'Accra Champion',
    trigger: 'Top 10 monthly volume',
    reward: 200,
    status: 'locked',
    progress: 25,
  },
  {
    id: 'kinshasa',
    name: 'Kinshasa Diamond',
    tier: 'Kinshasa Diamond',
    trigger: 'Hold 1,000+ DRC for 30 days',
    reward: 100,
    status: 'locked',
    progress: 15,
  },
  {
    id: 'addis',
    name: 'Addis Ababa Ally',
    tier: 'Addis Ababa Ally',
    trigger: 'Refer a friend who connects',
    reward: 30,
    status: 'locked',
    progress: 0,
  },
  {
    id: 'gaborone',
    name: 'Gaborone Gem',
    tier: 'Gaborone Gem',
    trigger: 'Reach 10,000 total DRC volume',
    reward: 150,
    status: 'locked',
    progress: 45,
  },
  {
    id: 'harare',
    name: 'Harare Hustler',
    tier: 'Harare Hustler',
    trigger: 'Swap every day for 7 days',
    reward: 75,
    status: 'locked',
    progress: 10,
  },
  {
    id: 'ouagadougou',
    name: 'Ouagadougou Oracle',
    tier: 'Ouagadougou Oracle',
    trigger: 'Predict a token price correctly',
    reward: 88,
    status: 'locked',
    progress: 0,
  },
];
